### ISSUE TITLE
[PE-D][Tester E] Unfriendly restriction on video name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103-F10-2/tp#267]
Cannot add video names that are not alphanumeric.

Sometimes this is required, for example:

![image.png](https://raw.githubusercontent.com/lhy-hoyin/ped/main/files/4a6bc322-8abe-41b2-965c-7af9825d881b.png)

![image.png](https://raw.githubusercontent.com/lhy-hoyin/ped/main/files/b65d6b67-3f52-4fb9-ac84-8d09896d0cfa.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: lhy-hoyin/ped#7

**Comment by hingen** [comment]
Noted. This is more of a "nice to have" rather than a "functionality bug".

We feel that giving the user more freedom is good but will have the tradeoff of making development harder and also opens the door for more malformed input attacks.

It will also make command parsing harder as we would have to carefully choose what is include-able and not include-able which also makes it harder to communicate to the user via the user guide.
